WebApplication7/WebApplication7/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using DataLayer.Entities;
using WebApplication7.Models;
namespace WebApplication7.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly DataContext _context;

        public DepartmentsController(DataContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.Departments.ToListAsync());
        }

        // GET: Departments/Details/5
        //public async Task<IActionResult> Details(int id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    //DepartmentModel ob = new DepartmentModel();

        //    //  ob.Count= _context.Employees.Where(e=> id==e.DepartmentId).Count();


        //    //var department = await _context.Departments
        //    //    .FirstOrDefaultAsync(m => m.Id == id);
        //    //if (department == null)
        //    //{
        //    //    return NotFound();
        //    //}
        //    //ob.DepartmentName = department.DepartmentName;
        //    //ob.Id = department.Id;


        //    return RedirectToRoute("employees/details"+id);
        //}

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DepartmentName")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var department = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.Id == id);
        }
    }
}

WebApplication7/WebApplication7/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using DataLayer.Entities;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly DataContext _context;

        public EmployeesController(DataContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index(int? id)

        {
            if (id != null)
            {
                if (ModelState.IsValid)
                {
                    var dataContext = _context.Employees.Where(e => id == e.DepartmentId).Select(e => new EmployeeModel
                    {
                        Id = e.Id,
                        UserName = e.UserName,
                        DOB = e.DOB,
                        Phone = e.Phone,
                        Emial = e.Emial,
                        Address = e.Address,
                        State = e.State,
                        City = e.City,
                        Zip = e.Zip,
                        DepartmentName = e.Departments.DepartmentName,
                        DepartmentId = e.DepartmentId
                    });

                    return View(await dataContext.ToListAsync());


                }
                else { return RedirectToRoute("Index"); }
            }
            else if (ModelState.IsValid)
            {



                var dataContext = _context.Employees.Include(e => e.Departments).Select(e => new EmployeeModel
                {
                    Id = e.Id,
                    UserName = e.UserName,
                    DOB = e.DOB,
                    Phone = e.Phone,
                    Emial = e.Emial,
                    Address = e.Address,
                    State = e.State,
                    City = e.City,
                    Zip = e.Zip,
                    DepartmentName = e.Departments.DepartmentName,
                    DepartmentId = e.DepartmentId
                });

                return View(await dataContext.ToListAsync());
            }

            else { return RedirectToRoute("Index"); }

        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var employee = await _context.Employees
                .Include(e => e.Departments)
                .FirstOrDefaultAsync(m => m.Id == id);

            EmployeeModel emp = new EmployeeModel();
            emp.Id = employee.Id;
            emp.UserName = employee.UserName;
            emp.DOB = employee.DOB;
            emp.City = employee.City;
            emp.Address = employee.Address;

            emp.Emial = employee.Emial;
            emp.State = employee.State;
            emp.Phone = employee.Phone;
            emp.DepartmentName = employee.Departments.DepartmentName;
            emp.Zip = employee.Zip;
            emp.DepartmentId = employee.DepartmentId;

            if (employee == null)
            {
                return NotFound();
            }
            return View(emp);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            ViewData["State"] = new SelectList(_context.States, "State", "State");

            ViewData["Id"] = new SelectList(_context.States, "Id", "Id");
            
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Id");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,DOB,Phone,Emial,Address,State,City,Zip,DepartmentId")] Employee employee)
        { 
          
            
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
          //  ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Id", employee.DepartmentId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            ViewData["State"] = new SelectList(_context.States, "State", "State");
            

            ViewData["Id"] = new SelectList(_context.States, "Id", "Id");

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Id");

            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            EmployeeModel emp = new EmployeeModel();
            emp.Id = employee.Id;
            emp.UserName = employee.UserName;
            emp.DOB = employee.DOB;
            emp.City = employee.City;
            emp.Address = employee.Address;
            ViewData["City"] = new SelectList(_context.Cities.Where(x => x.States.State == employee.State), "City", "City");
            emp.Emial = employee.Emial;
            emp.State = employee.State;
            emp.Phone = employee.Phone;
            emp.Zip = employee.Zip;
            emp.DepartmentId = employee.DepartmentId;
            emp.DepartmentName = employee.Departments.DepartmentName;


            return View(emp);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Id", employee.DepartmentId);
            return View(employee);
        }

        // GET: Employees/Delete/5

        public async Task<IActionResult> Delete(int? EmployeeId)
        {
            if (EmployeeId == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Departments)
                .FirstOrDefaultAsync(m => m.Id == EmployeeId);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
       
        public IActionResult FindCity(string id)
        {
            //var sId = _context.States.Where(z => z.State == name).Select(x => x.Id);
            //int id = Convert.ToInt32(sId);
            var city = _context.Cities.Where(z=>id==z.States.State).Select(x => new 
            {
                
                 Id = x.Id,
                City = x.City

            });
           
            return new JsonResult(city);

        }
        public IActionResult FindId(string id)
        {
            var city = _context.Departments.Where(z => id == z.DepartmentName).Select(x => new
            {

                name = x.Id,
                
            });

            return new JsonResult(city);

        }
    }
}

WebApplication7/WebApplication7/Views/Departments/Create.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication7/WebApplication7/Views/Departments/Delete.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication7/WebApplication7/Views/Departments/Details.cshtml
@model WebApplication7.Models.DepartmentModel



@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication7/WebApplication7/Views/Departments/Edit.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Details</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication7/WebApplication7/Views/Departments/Index.cshtml
@model IEnumerable<DataLayer.Entities.Department>

@{
    ViewData["Title"] = "Index";
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<div class="text-left">
    <h2>Data &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <a class="btn btn-primary" asp-action="Create">Create New</a> </h2> 
</div>
<br>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
            @Html.DisplayNameFor(model => model.DepartmentName)
                
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-controller="Employees" asp-action="Index" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.DepartmentName)</a>
            </td>
            <td>
                <a  class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
               |
                <a class="btn btn-danger" onclick="myFunction(@item.Id)">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<script>



    function myFunction(id) {

        var r = confirm("Confirm Delete?");
        if (r == true) {
            x(id);
        }
    }


    function x(id) {


        $.ajax({
            type: "DELETE",
            url: "https://localhost:44343/api/Departments/" +id,
            contentType: "Application/json;charset=utf-8",
            success: function () { window.location.reload(); }
        });


    }

</script>